config/routes.rb
Rails.application.routes.draw do
  get 'allproducts' => 'inventory#all_products'
  get 'product' => 'inventory#one_product'
  get 'categorized' => 'inventory#by_category'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_products
    @allproducts = Product.all
  end

  def one_product
    @product = Product.find_by(params[:id])
  end

  def by_category
    @category = params[:category]
    @products = Product.where(category: @category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventory/all_products.html.erb
<h1>Inventory - All Products in our Store</h1>
<hr>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th>Price</th>
    <th></th>
    <th>Category</th>
  </tr>

    <% @allproducts.each do |product| %>
    <tr>
      <td><%= link_to product.name, product_path(id: product.id)  %></td>
      <td></td>
      <td><%= product.price %></td>
      <td></td>
      <td><%= link_to product.category, categorized_path(category: product.category)  %></td>
    <% end %>
  </tr>
</table>

app/views/inventory/by_category.html.erb
<h1>Our Entire <%= @category %> Stock:</h1>
<hr>
<table>
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Category</th>
	</tr>

	<% @products.each do |product| %>
	<tr>
		<td><%= product.name %></td>
		<td><%= number_to_currency(product.price) %></td>

	</tr>
	<% end %>
</table>

app/views/inventory/one_product.html.erb
<h1>Product:  <%= @product.name %></h1>
<hr>
<p>
	<strong>Price: </strong>
	<%= number_to_currency(@product.price) %>
</p>

<p>
	<strong>Category</strong>
	<%= link_to @product.category, categorized_path(category: @product.category) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurnitureStore2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>